export const CONSTANTS = {
    FIRST_TIME_LOGIN : "You have logged in for the first time. Please change the password.",
    PASSWORD_EXPIRED :"Your password has expired",
    ENTER_PWD :'Enter Password',
    HOMEPAGE_ITINERARY : "Create itinerary & raise a request for Work Travel",
    CONTACT_INFO: 'Contact Information',
    CONTACT_US:'Contact us',
    START_TRIP: 'Start a new trip',
    PERSONAL_TAVEL : 'book personal travel',
    FLIGHT : 'Flights',
    HOTEL : 'Hotels',
    GUEST_HOUSE : 'Guest House',
    HOLIDAY_HOME: 'Holiday Homes',
    CORPORATE_LEISURE : 'Corporate Leisure Program',
    MY_REQUEST:'My Requests',
    MY_TRIP:'My Trips',
    MY_APPROVAL:'My Approvals',
    CALL_US :'Call us on',
    WRITE_US: 'Write to us',
    ESCALATION_MATRIX : 'Escalation Matrix',
    MY_PROFILE : 'My Profile',
    CONFIRM : 'Confirm',
    INCORRECT_PWD_MSG :'Incorrect password or the user Id provided is wrong.',
    LOGIN_MSG :'Login to Your Company Account',
    ENTER_LOGIN_ID: 'Login ID / Email Address',
    LOGIN_PLCAEHOLDER : 'Enter your login id or email address',
    OTP_MSG :'One Time Password (OTP) has been sent to your registered email address and mobile number.',
    MYTRIPS : 'My Trips',
    VIEW_ALL : 'View all',
    REJECT_REQUEST : "Reject request",
    REASON_REJECTION : "Reason for rejection" ,
    CNF_REJECT_REQUEST  : "Confirm and reject request",
    REQUEST_SENT_TO :"Request sent to",
    TRIP_ID : "Trip ID #",
    TRIP_REQUEST : "Trip Requests",
    FOR_YOU_TO_APPROVE : "FOR YOU TO APPROVE",
    RAISED_BY_YOU : "RAISED BY YOU",
    PASSWORDMISMATCH : "Passwords didn’t match!"
    };